service: dd-api

plugins:
  - serverless-webpack
  - serverless-domain-manager
custom:
  aws_account: ${file(./src/env.yml):${self:custom.stage}.AWS_ACCOUNT}
  stage: ${env:SLS_STAGE, opt:stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    rest:
      domainName: ${file(./src/env.yml):${self:custom.stage}.DOMAIN_NAME, ''}
      stage: ${self:custom.stage}
      basePath: api
      certificateName: ${file(./src/env.yml):${self:custom.stage}.SSL_DOMAIN_CERTIFICATE}
      createRoute53Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements: ${file(./roles.yml)}
  region: us-east-1
  stage: ${self:custom.stage}
  environment: ${file(./src/env.yml):${self:custom.stage}}

package:
  exclude:
    - tests/**

functions: ${file(./src/serverless-dynamic.js):functions}

resources:
  Resources: ${file(./src/resources.yml)}
